{{ range $cronjobName, $cronjobValues := .Values.cronjobs }}
{{- $volumesHolder := dict }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "<CHARTNAME>.cronjobName" (dict "root" $ "cronjob" $cronjobName) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
  {{- with $cronjobValues.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ required "cronjob %s requires schedule to be defined" $cronjobValues.schedule | quote}}
  suspend: {{ default "false" $cronjobValues.suspend }}
  {{- with $cronjobValues.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  {{- with $cronjobValues.concurrencyPolicy }}
  concurrencyPolicy: {{ . }}
  {{- end }}
  {{- with $cronjobValues.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $cronjobValues.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ . }}
  {{- end }}
  {{- with $cronjobValues.timeZone }}
  timeZone: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      {{- with $cronjobValues.backoffLimit }}
      backoffLimit: {{ . }}
      {{- end }}
      {{- with $cronjobValues.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ . }}
      {{- end }}
      template:
        spec:
          restartPolicy: {{ default "Never" $cronjobValues.restartPolicy }}
          {{- with (default $.Values.imagePullSecrets $cronjobValues.imagePullSecrets) }}
          imagePullSecrets:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "<CHARTNAME>.serviceAccountName" $ }}
          securityContext:
            {{- toYaml (default  $.Values.podSecurityContext $cronjobValues.podSecurityContext) | nindent 12 }}
          {{- with $cronjobValues.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          {{- range $i, $container := (required (printf "cronjob %s must define .containers dictionary" $cronjobName) $cronjobValues.containers) }}
            - {{- include "<CHARTNAME>.containerManifest" (dict "root" $ "containerName" $i "container" $container "objectDescription" "Cronjob" "objectName" (include "<CHARTNAME>.cronjobName" (dict "root" $ "cronjob" $cronjobName)) "volumesHolder" $volumesHolder ) | nindent  14 }}
          {{- end }}
          {{- with $cronjobValues.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $cronjobValues.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $cronjobValues.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $volumesHolder $cronjobValues.extraVolumes }}
          volumes:
            {{- range $containers, $persistence := $volumesHolder }}
            {{- range $volName, $volSpec := $persistence }}
            - name: {{ $volName }}
              persistentVolumeClaim:
                claimName: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "volumeName" $volName "volumeSpec" $volSpec) }}
            {{- end }}
            {{- end }}
            {{- range $cronjobValues.extraVolumes }}
            - {{ toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
{{- end }}