{{ range $jobName, $jobValues := .Values.jobs }}
{{- $volumesHolder := dict }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "<CHARTNAME>.jobName" (dict "root" $ "job" $jobName) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
  {{- with $jobValues.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $jobValues.backoffLimit }}
  backoffLimit: {{ . }}
  {{- end }}
  {{- with $jobValues.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}  
  template:
    spec:  
      restartPolicy: {{ default "Never" $jobValues.restartPolicy }}
      {{- with (default $.Values.imagePullSecrets $jobValues.imagePullSecrets) }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "<CHARTNAME>.serviceAccountName" $ }}
      securityContext:
        {{- toYaml (default  $.Values.podSecurityContext $jobValues.podSecurityContext) | nindent 8 }}
      {{- with $jobValues.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- range $i, $container := (required (printf "Job %s must define .containers dictionary" $jobName) $jobValues.containers) }}
        - name: {{ include "<CHARTNAME>.containerName" (dict "prefix" $jobName "container" $i) }}
          securityContext:
            {{- toYaml ( default dict $container.securityContext ) | nindent 12 }}
          image: "{{ required (printf "job %s.containers.%s.image.repository is required" $jobName $i) (required (printf "job %s.containers.%s.image.repository is required" $jobName $i) $container.image).repository }}:{{ $container.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ default $.Values.image.pullPolicy $container.image.pullPolicy }}
          {{- if $container.env }}
          env:
            {{- range $key, $val := $container.env }}
            - name: {{ $key }}
              value: {{ tpl $val $ | quote }}
            {{- end }}
          {{- end }}
          {{- if and $container.config (or $container.config.env $container.config.secretEnv $container.extraEnvFrom) }}
          envFrom:
            {{- if $container.config.env }}
            - configMapRef:
                name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" (include "<CHARTNAME>.containerName" (dict "prefix" $jobName "container" $i))) }}
            {{- end }}
            {{- if $container.config.secretEnv }}
            - secretRef:
                name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" (include "<CHARTNAME>.containerName" (dict "prefix" $jobName "container" $i))) }}
            {{- end }}
            {{- if $container.extraEnvFrom }}
            {{- toYaml $container.extraEnvFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with $container.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.startupProbe }}
          startupProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml ( default dict $container.resources ) | nindent 12 }}
          {{- if $container.persistence }}
          {{- $_ := set $volumesHolder $i $container.persistence }}
          {{- end }}
          {{- if or $container.persistence $container.extraVolumeMounts }}
          volumeMounts:
            {{- range $volName, $volSpec := $container.persistence }}
            - name: {{ $volName }}
              mountPath: {{ required (printf "jobs.%s.containers[%d].persistence.%s.mountPath must be set" $jobName $i $volName) $volSpec.mountPath }}
            {{- end }}
            {{- range $extraMount := $container.extraVolumeMounts }}
            - {{ toYaml $extraMount | nindent 14 }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- with $jobValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $jobValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $jobValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $volumesHolder $jobValues.extraVolumes }}
      volumes:
        {{- range $containers, $persistence := $volumesHolder }}
        {{- range $volName, $volSpec := $persistence }}
        - name: {{ $volName }}
          persistentVolumeClaim:
            claimName: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "volumeName" $volName "volumeSpec" $volSpec) }}
        {{- end }}
        {{- end }}
        {{- range $jobValues.extraVolumes }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end }}