{{- range $i, $container := .Values.containers }}
{{- range $volName, $volSpec := $container.persistence }}
{{- if and $container.persistence (not $volSpec.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if $volSpec.annotations }}
  annotations:
    {{- toYaml $volSpec.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "container" $i "volumeName" $volName) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  accessModes:
  {{- range $volSpec.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- with $volSpec.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $volSpec.storageClassName }}
  storageClassName: {{ $volSpec.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
