{{- $cronjobContainers := dict -}}
{{- range $cronjobName, $cronjobValues := .Values.cronjobs }}
{{- range $i, $container := $cronjobValues.containers }}
  {{- $_ := set $cronjobContainers (include "<CHARTNAME>.containerName" (dict "prefix" $cronjobName "container" $i)) $container -}}
{{- end -}}
{{- end -}}
{{- $jobContainers := dict -}}
{{- range $jobName, $jobValues := .Values.jobs }}
{{- range $i, $container := $jobValues.containers }}
  {{- $_ := set $jobContainers (include "<CHARTNAME>.containerName" (dict "prefix" $jobName "container" $i)) $container -}}
{{- end -}}
{{- end -}}
{{- $extraDeployentContainers := dict -}}
{{- range $extraDeploymentName, $extraDeploymentValues := .Values.extraDeployments }}
{{- range $i, $container := $extraDeploymentValues.containers }}
  {{- $_ := set $extraDeployentContainers (include "<CHARTNAME>.containerName" (dict "prefix" $extraDeploymentName "container" $i)) $container -}}
{{- end -}}
{{- end -}}
{{- range $i, $container := (merge $jobContainers $cronjobContainers $extraDeployentContainers .Values.containers ) }}
{{- range $volName, $volSpec := $container.persistence }}
{{- if and $container.persistence (not $volSpec.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  {{- if $volSpec.annotations }}
  annotations:
    {{- toYaml $volSpec.annotations | nindent 4 }}
  {{- end }}
  name: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "container" $i "volumeName" $volName "volumeSpec" $volSpec) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  accessModes:
  {{- range (required (printf "Persistence for container %s must define accessModes" $i) $volSpec.accessModes) }}
    - {{ . | quote }}
  {{- end }}
  {{- with $volSpec.resources }}
  resources:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $volSpec.storageClassName }}
  storageClassName: {{ $volSpec.storageClassName | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
