{{- range $i, $container := .Values.containers }}
{{- if and $container.config $container.config.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" $i) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
stringData: {{- tpl (( default dict $container.config.secretEnv ) | toYaml) . | nindent 2 }}
{{- end }}
{{- end }}
