{{- $cronjobContainers := dict -}}
{{- range $cronjobName, $cronjobValues := .Values.cronjobs }}
{{- range $i, $container := $cronjobValues.containers }}
  {{- $_ := set $cronjobContainers $i $container -}}
{{- end -}}
{{- end -}}
{{- $jobContainers := dict -}}
{{- range $jobName, $jobValues := .Values.jobs }}
{{- range $i, $container := $jobValues.containers }}
  {{- $_ := set $jobContainers $i $container -}}
{{- end -}}
{{- end -}}
{{- $extraDeploymentContainers := dict -}}
{{- range $deploymentName, $deploymentValues := .Values.extraDeployments }}
{{- range $i, $container := $deploymentValues.containers }}
  {{- $_ := set $extraDeploymentContainers $i $container -}}
{{- end -}}
{{- end -}}
{{- range $i, $container := (merge $jobContainers $cronjobContainers $extraDeploymentContainers .Values.containers ) }}
{{- if and $container.config $container.config.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" $i) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
  {{- with $container.config.secretEnvAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 
stringData: {{- tpl (( default dict $container.config.secretEnv ) | toYaml) . | nindent 2 }}
{{- end }}
{{- end }}
